### ISSUE TITLE
Feature request: select folder for decrypted file

### ISSUE THREAD

**Issue by habeasdata404** [jkotra/unlockr#12]
@jkotra, unlockR is a lightweight and extremely useful app!

It would be great if we could select a folder to save the decrypted file in.

**Comment by soumyaDghosh** [comment]
If anyone isn't working, I would like to implement this

**Comment by jkotra** [comment]
> If anyone isn't working, I would like to implement this

I can definitely take a look at your work, I'm expecting you are familiar with libraries that are used in this project.

**Comment by soumyaDghosh** [comment]
I am snap packager of this app, FYI. So, yes I know :slightly_smiling_face:  
Guess you missed #14

**Comment by jkotra** [comment]
implemented in #12 and part of `0.9.0`
