### ISSUE TITLE
Error handle for null folder

### ISSUE THREAD

**Issue by soumyaDghosh** [jkotra/unlockr#17]
Hii, I just tested your implementation, the problem is, there is no way for error handling for not choosing a folder, like I did in my one. And I must say, this implementation really doesn't look good. None will be able to know that you select the save folder, unless you click on the hamburger menu. Kindly look into these. Do you really think this is a better implementation?

**Comment by jkotra** [comment]
Thanks for the bug report, i have released a hot fix - `0.9.1`

 > None will be able to know that you select the save folder, unless you click on the hamburger menu.

While the option was not really explicit in UI, someone who is looking for it will be able to find it. Also, i think it's more inline with gnome HIG.

**Comment by soumyaDghosh** [comment]
> While the option was not really explicit in UI, someone who is looking for it will be able to find it. Also, i think it's more inline with gnome HIG.

Ummm... Not sure about Gnome HIG and these things. It's your design choice. So, closing this as completed.
