### ISSUE TITLE
Licence at READ.me

### ISSUE THREAD

**Issue by ovari** [jkotra/unlockr#4]
Can you please list the license ([GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html), [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html)) for this software on the [READ.me](https://www.gnu.org/licenses/gpl-3.0.en.html)?

Thank you

**Comment by jkotra** [comment]
added LICENSE file. (de76840d91d2611275bed049e7c13d11729a91b3)

I will improve README in future, along with information about license.

**Comment by ovari** [comment]
> I will improve README in future

Please add a section on how to translate.

Thank you once again

**Comment by jkotra** [comment]
> Please add a section on how to translate.

please refer: https://github.com/jkotra/unlockr/blob/main/po/README.md

**Comment by jkotra** [comment]
added License section to README.
