### ISSUE TITLE
No Italian language available

### ISSUE THREAD

**Issue by albanobattistella** [jkotra/unlockr#7]
HI,

in the last version Italian language is not available.
thanks.
A.

**Comment by jkotra** [comment]
fixed in [0.8](https://github.com/jkotra/unlockr/tree/0.8).

![Screenshot from 2022-11-09 19-24-03](https://user-images.githubusercontent.com/29590316/200862313-7d6ded4c-af16-4013-b2b8-2a8649b3a1e7.png)

thanks for reporting :+1: .
